### ISSUE TITLE
Suggestion to add a build check

### ISSUE THREAD

**Issue by kian99** [canonical/documentation-workflows#14]
# Description

In our project we found that changes to our documentation would pass CI and then fail to be built on read-the-docs. To address this we added the following to our project:
In `Makefile`:
```
check-html-build: install
	. $(VENV); $(SPHINXBUILD) -b dirhtml "$(SOURCEDIR)" "$(BUILDDIR)" -E --fail-on-warning --keep-going $(SPHINXOPTS)
```
And an extra job in our github workflow:
```
build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with warnings as errors
        run: make check-html-build
```
This way we are emulating the same steps as read-the-docs when it comes to building the docs with warnings treated as errors. Would this be a good addition to the documentation-workflows and potentially starter pack?
