### ISSUE TITLE
Improve Failure Reporting

### ISSUE THREAD

**Issue by ColmBhandal** [canonical/documentation-workflows#5]
[De-parallelising our workflow](https://github.com/canonical/documentation-workflows/pull/4) saved time / GitHub runners, but introduced the problem that the workflow step failures are not reported accurately. Only the first failed step shows as failed.

A potential improvement would be to aggregate all steps' statuses and report them in a final step that runs after all others. Something like this:

```
name: Automatic documentation checks

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Working directory'
        required: true
        type: string
    outputs:
      spellcheck-result:
        description: "Result of the spelling check"
        value: ${{ jobs.docchecks.outputs.result_spelling }}
      woke-result:
        description: "Result of the inclusive language check"
        value: ${{ jobs.docchecks.outputs.result_woke }}
      linkcheck-result:
        description: "Result of the link check"
        value: ${{ jobs.docchecks.outputs.result_links }}

jobs:
  docchecks:
    name: Run documentation checks
    runs-on: ubuntu-latest
    outputs:
      result_spelling: ${{ steps.spellcheck-step.outcome }}
      result_woke: ${{ steps.woke-step.outcome }}
      result_links: ${{ steps.linkcheck-step.outcome }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Spell Check
        id: spellcheck-step
        uses: canonical/documentation-workflows/spellcheck@main
        with:
          working-directory: ${{ inputs.working-directory }}
        continue-on-error: true

      - name: Inclusive Language Check
        id: woke-step
        uses: canonical/documentation-workflows/inclusive-language@main
        with:
          working-directory: ${{ inputs.working-directory }}
        continue-on-error: true

      - name: Link Check
        id: linkcheck-step
        uses: canonical/documentation-workflows/linkcheck@main
        with:
          working-directory: ${{ inputs.working-directory }}
        continue-on-error: true

      - name: Check Step Results
        run: |
          errors=()
          if [ ${{ steps.spellcheck-step.outcome }} == 'failure' ]; then
            echo "Spell Check failed"
            errors+=("Spell Check")
          fi
          if [ ${{ steps.woke-step.outcome }} == 'failure' ]; then
            echo "Inclusive Language Check failed"
            errors+=("Inclusive Language Check")
          fi
          if [ ${{ steps.linkcheck-step.outcome }} == 'failure' ]; then
            echo "Link Check failed"
            errors+=("Link Check")
          fi

          if [ ${#errors[@]} -gt 0 ]; then
            echo "Failing the job due to errors in steps: ${errors[@]}"
            exit 1
          fi
```
