### ISSUE TITLE
use stable versions instead of `main` branch for consistent checking result

### ISSUE THREAD

**Issue by tang-mm** [canonical/documentation-workflows#6]
It's great that we can benefit from new features by simply referencing this repository. Meanwhile, a concern about using the `main` branch is that frequent changes in the branch may cause variances in the test results in the doc repository. If the base pipeline changes or upgrades between two commits in the same PR, it might be hard to trace on the developer side. 

A proposal is to introduce tags on a stable version so that in the workflow definition file, we can choose to use the latest stable version, and only upgrade the version when the next stable version is available.

```yaml
jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yml@main
```
