### ISSUE TITLE
Use 20.04 (instead of 'latest')

### ISSUE THREAD

**Issue by rkratky** [canonical/documentation-workflows#7]
GH Action runners using 20.04 are provisioned faster, whjich allows for a quicker turn around with the CI. I suggest changing the following to 20.04:
```
jobs:
  docchecks:
    name: Run documentation checks
    runs-on: ubuntu-latest
```
to 
```
jobs:
  docchecks:
    name: Run documentation checks
    runs-on: ubuntu-20.04
```
